/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2019 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */
#include<stdint.h> //this is used for uint32_t declaration

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


#define RCC_BASE_ADDR 				0X40023800UL
#define RCC_CFGR_REG_OFFSET 		0X44UL
#define RCC_CFGR_REG_ADDR 			(RCC_BASE_ADDR + RCC_CFGR_REG_OFFSET)

#define GPIOA_BASE_ADDR 0x40020000UL

int main(void)
{
	uint32_t *pRccCfgReg = (uint32_t*) RCC_CFGR_REG_ADDR;

	//1. Configure the RCC_CFGR MCO1 bit fields to select HSI as clock output source
	*pRccCfgReg &= ~(0x3 << 21); //Clear 21st and 22nd bit positions

	//2. COnfigure the PA8 to AF0 mode to behave as MCO1 signal (Alternate function of 8th pin in port A)

	//a. Enable the peripheral clock for GPIOA peripheral
	uint32_t *pRCCAhb1Enr = (uint32_t *) (RCC_BASE_ADDR + 0x30);
	*pRCCAhb1Enr |= (1<<0); ///Setting 0th bit as 1 i.e enable GPIOA peripheral clock

	//b. Configure the mode of GPIOA as alternate function mode
	uint32_t *pGPIOAModeReg = (uint32_t*)(GPIOA_BASE_ADDR + 00);
	*pGPIOAModeReg &= ~(0x3 <<16); //clear bits 16 and 17
	*pGPIOAModeReg &= ~(0x2 <<16); //Set '10' on 17 and 16 so that it is initialized to alternate function

	//c. configure the alternate function register to set as mode for PA.8
	 uint32_t *pGPIOAAltFunHighReg = (uint32_t*) (GPIOA_BASE_ADDR + 0x24);
	 *pGPIOAAltFunHighReg &= ~(0xf << 0);



	for(;;);


}


void FMC_IRQHandler(void)
{

}
